### ISSUE TITLE
ImportWarning from extension folder

### ISSUE THREAD

**Issue by davidszotten** [maxmind/MaxMind-DB-Reader-python#31]
Could we consider changing the name of the folder with the extension source to be different than then name of the extension? currently, if there is no extension built, we get an import warning from python from `import maxminddb.extension`

**Comment by oschwald** [comment]
Thanks for raising this. We have not seen this warning. Would it be possible for you to provide steps to reproduce it, including Python version, etc? Thanks!

**Comment by davidszotten** [comment]
hm, so i think this was caused by `pytest` and `pytest-warnings`. and it turns out it's fixed in a newer version. apologies for the noise

**Comment by craigds** [comment]
```
System check identified no issues (4 silenced).
October 29, 2018 - 02:03:08
Django version 1.11.16, using settings 'myapp.settings'
Starting development server at http://127.0.0.1:<port>/
Quit the server with CONTROL-C.
/kx/app/venv/local/lib/python2.7/site-packages/maxminddb/__init__.py:7: ImportWarning: Not importing directory '/kx/app/venv/local/lib/python2.7/site-packages/maxminddb/extension': missing __init__.py
  import maxminddb.extension
```

Not sure what version @davidszotten  had, but we have 1.4.1 (the latest) and this is still present.

**Comment by craigds** [comment]
(python 2.7.6, if that helps.)

**Comment by oschwald** [comment]
@craigds, I am still not able to reproduce this on 2.7.15:

```
$ pip instal maxminddb --verbose
...
   ***************************************************************************
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Plain-Python build succeeded.
    ***************************************************************************
done
  Removing source in /tmp/pip-build-v7sKjb/maxminddb
Successfully installed maxminddb-1.4.1
Cleaning up...
$ python
Python 2.7.15 (default, Sep 21 2018, 10:32:37) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import maxminddb
>>> db = maxminddb.open_database('/usr/local/share/GeoIP/GeoIP2-City.mmdb')
>>> db.get('1.1.1.1')
...
```

**Comment by oschwald** [comment]
Never mind. I was able to reproduce this with `-Wdefault`.
